---
- name: Read Prowlarr tags
  ansible.builtin.uri:
    url: "http://{{ media_host_ip }}:{{ media_ports.prowlarr }}/api/v1/tag"
    headers:
      X-Api-Key: "{{ media_prowlarr_api_key }}"
    return_content: true
  register: media_prowlarr_tags
  no_log: true

- name: Create FlareSolverr Prowlarr tag
  ansible.builtin.uri:
    url: "http://{{ media_host_ip }}:{{ media_ports.prowlarr }}/api/v1/tag"
    method: POST
    headers:
      X-Api-Key: "{{ media_prowlarr_api_key }}"
    body_format: json
    body:
      label: "{{ media_flaresolverr_tag }}"
    status_code: 201
  when: >-
    media_flaresolverr_tag not in
    (media_prowlarr_tags.json | map(attribute='label') | list)
  no_log: true

- name: Read updated Prowlarr tags
  ansible.builtin.uri:
    url: "http://{{ media_host_ip }}:{{ media_ports.prowlarr }}/api/v1/tag"
    headers:
      X-Api-Key: "{{ media_prowlarr_api_key }}"
    return_content: true
  register: media_prowlarr_updated_tags
  no_log: true

- name: Select FlareSolverr Prowlarr tag ID
  ansible.builtin.set_fact:
    media_flaresolverr_tag_id: >-
      {{ (media_prowlarr_updated_tags.json
          | selectattr('label', 'equalto', media_flaresolverr_tag)
          | map(attribute='id') | first) }}
  no_log: true

- name: Define FlareSolverr Prowlarr proxy
  ansible.builtin.set_fact:
    media_flaresolverr_proxy:
      name: FlareSolverr
      fields:
        - name: host
          value: "http://flaresolverr:{{ media_flaresolverr_port }}/"
        - name: requestTimeout
          value: "{{ media_flaresolverr_request_timeout }}"
      implementationName: FlareSolverr
      implementation: FlareSolverr
      configContract: FlareSolverrSettings
      tags:
        - "{{ media_flaresolverr_tag_id }}"
  no_log: true

- name: Read Prowlarr indexer proxies
  ansible.builtin.uri:
    url: "http://{{ media_host_ip }}:{{ media_ports.prowlarr }}/api/v1/indexerProxy"
    headers:
      X-Api-Key: "{{ media_prowlarr_api_key }}"
    return_content: true
  register: media_prowlarr_indexer_proxies
  no_log: true

- name: Test new FlareSolverr proxy from Prowlarr
  ansible.builtin.uri:
    url: "http://{{ media_host_ip }}:{{ media_ports.prowlarr }}/api/v1/indexerProxy/test"
    method: POST
    headers:
      X-Api-Key: "{{ media_prowlarr_api_key }}"
    body_format: json
    body: "{{ media_flaresolverr_proxy }}"
    status_code: 200
  when: >-
    'FlareSolverr' not in
    (media_prowlarr_indexer_proxies.json | map(attribute='name') | list)
  no_log: true

- name: Add FlareSolverr proxy to Prowlarr
  ansible.builtin.uri:
    url: "http://{{ media_host_ip }}:{{ media_ports.prowlarr }}/api/v1/indexerProxy"
    method: POST
    headers:
      X-Api-Key: "{{ media_prowlarr_api_key }}"
    body_format: json
    body: "{{ media_flaresolverr_proxy }}"
    status_code: 201
  when: >-
    'FlareSolverr' not in
    (media_prowlarr_indexer_proxies.json | map(attribute='name') | list)
  no_log: true
