---
media_stack_dir: /opt/media-stack
media_stack_config_dir: "{{ media_stack_dir }}/config"
media_data_mount: /data
media_data_disk: /dev/sdb
media_lan_cidr: 192.168.40.0/24
media_host_ip: "{{ ansible_host | default('192.168.40.131') }}"
media_puid: 1000
media_pgid: 1000
media_umask: "002"
media_timezone: Europe/Warsaw

media_gluetun_image: qmcgaw/gluetun:v3.41.1
media_qbittorrent_image: lscr.io/linuxserver/qbittorrent:latest
media_sonarr_image: lscr.io/linuxserver/sonarr:latest
media_radarr_image: lscr.io/linuxserver/radarr:latest
media_prowlarr_image: lscr.io/linuxserver/prowlarr:latest
media_flaresolverr_image: ghcr.io/flaresolverr/flaresolverr:v3.5.0
media_bazarr_image: lscr.io/linuxserver/bazarr:latest
media_jellyfin_image: jellyfin/jellyfin:10.11.11
media_seerr_image: ghcr.io/seerr-team/seerr:v3.3.0

media_mullvad_server_countries: Poland
media_mullvad_server_cities: ""
media_mullvad_owned_only: "no"
media_mullvad_wireguard_private_key: "{{ vault_media_mullvad_wireguard_private_key | default('') }}"
media_mullvad_wireguard_addresses: "{{ vault_media_mullvad_wireguard_addresses | default('') }}"

media_qbittorrent_admin_user: admin
media_qbittorrent_admin_password: "{{ vault_media_qbittorrent_admin_password | default('') }}"
media_jellyfin_admin_user: admin
media_jellyfin_admin_password: "{{ vault_media_jellyfin_admin_password | default('') }}"
media_seerr_admin_email: admin@lab.invalid

media_stack_pull_images: false
media_configure_integrations: true
media_jellyfin_enable_qsv_when_available: true
media_flaresolverr_port: 8191
media_flaresolverr_tag: flaresolverr
media_flaresolverr_request_timeout: 60
media_bazarr_default_profile_name: polen
media_bazarr_default_profile_languages:
  - pl
  - en
media_bazarr_default_profile_items:
  - id: 1
    language: pl
    audio_exclude: "False"
    audio_only_include: "False"
    hi: "False"
    forced: "False"
  - id: 2
    language: en
    audio_exclude: "False"
    audio_only_include: "False"
    hi: "False"
    forced: "False"
media_bazarr_enabled_providers:
  - subdl
  - yifysubtitles

media_ports:
  jellyfin: 8096
  seerr: 5055
  sonarr: 8989
  radarr: 7878
  prowlarr: 9696
  bazarr: 6767
  qbittorrent: 8080
  gluetun_health: 9999

media_log_max_size: 10m
media_log_max_file: 3
