output "vms" {
  description = "Map of all managed VMs with their core attributes"
  value = {
    for k, m in module.vms : k => {
      vm_id = m.vm_id
      name  = m.name
      ip    = m.ipv4_address
      fqdn  = m.fqdn
      tags  = m.tags
    }
  }
}

# Rendered as a ready-to-use Ansible inventory (INI format).
# Consumed by `make inventory` -> ansible/inventories/prod/hosts.generated
output "ansible_inventory" {
  description = "Ansible inventory (INI) generated from VM tags"
  value = join("\n", concat(
    [
      "# Auto-generated by Terraform — do not edit by hand.",
      "# Run `make inventory` to regenerate.",
      "",
      "[all:vars]",
      "ansible_user=homelab",
      "ansible_python_interpreter=/usr/bin/python3",
      "",
      "[all]",
    ],
    [
      for k, v in module.vms :
      "${v.name} ansible_host=${v.ipv4_address}"
    ],
    flatten([
      for tag in distinct(flatten([for v in module.vms : v.tags])) : tag == "terraform" ? [] : concat(
        [""],
        ["[${replace(tag, "-", "_")}]"],
        [
          for k, v in module.vms :
          "${v.name} ansible_host=${v.ipv4_address}"
          if contains(v.tags, tag)
        ],
      )
    ]),
  ))
}
