---
- name: Ensure Valheim server directory exists
  ansible.builtin.file:
    path: "{{ valheim_server_dir }}"
    state: directory
    owner: homelab
    group: homelab
    mode: '0755'

- name: Ensure Valheim save directory exists
  ansible.builtin.file:
    path: "{{ valheim_save_dir }}/worlds_local"
    state: directory
    owner: homelab
    group: homelab
    mode: '0755'
    recurse: true

- name: Deploy Valheim start script
  ansible.builtin.template:
    src: start_valheim.sh.j2
    dest: "{{ valheim_server_dir }}/start_valheim.sh"
    owner: homelab
    group: homelab
    mode: '0755'
  notify: Restart valheim-server

- name: Deploy Valheim systemd service
  ansible.builtin.template:
    src: valheim.service.j2
    dest: /etc/systemd/system/valheim.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart valheim-server

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure Valheim service is enabled and running
  ansible.builtin.systemd:
    name: valheim
    enabled: true
    state: started

- name: Open Valheim UDP ports in firewalld
  ansible.posix.firewalld:
    port: "2456-2457/udp"
    permanent: true
    state: enabled
    immediate: true
    zone: public
