---
all:
  vars:
    ansible_user: homelab
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

  children:
    docker_hosts:
      hosts:
        dns-01:
          ansible_host: 192.168.60.141
        proxy-01:
          ansible_host: 192.168.60.142
        app-01:
          ansible_host: 192.168.60.143
        monitor-01:
          ansible_host: 192.168.60.144
        jelly-01:
          ansible_host: 192.168.60.131

    pihole:
      hosts:
        dns-01:

    proxy:
      hosts:
        proxy-01:

    apps:
      hosts:
        app-01:

    nagios:
      hosts:
        monitor-01:

    monitoring:
      hosts:
        monitor-01:

    media:
      hosts:
        jelly-01:

    kubernetes:
      hosts:
        k8s-cp1:
          ansible_host: 192.168.60.151
        k8s-w1:
          ansible_host: 192.168.60.152
        k8s-w2:
          ansible_host: 192.168.60.153

    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.60.10
          ansible_user: root
