---
all:
  vars:
    ansible_user: homelab
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

  children:
    docker_hosts:
      hosts:
        jelly-01:
          ansible_host: 192.168.60.131
        dns-01:
          ansible_host: 192.168.60.141
        proxy-01:
          ansible_host: 192.168.60.142
        app-01:
          ansible_host: 192.168.60.143
        monitor-01:
          ansible_host: 192.168.60.144

    jellyfin:
      hosts:
        jelly-01:

    pihole:
      hosts:
        dns-01:

    proxy:
      hosts:
        proxy-01:

    apps:
      hosts:
        app-01:

    nagios:
      hosts:
        monitor-01:
