---
services:
  web:
    container_name: coming-soon
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - public-proxy

networks:
  public-proxy:
    external: true
    name: public-proxy
