---
- name: Create Portainer directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: homelab
    group: homelab
    mode: '0755'
  loop:
    - /opt/portainer
    - /opt/portainer/data

- name: Deploy Portainer Docker Compose
  ansible.builtin.template:
    src: portainer.yml.j2
    dest: /opt/portainer/docker-compose.yml
    owner: homelab
    group: homelab
    mode: '0644'
  notify: Restart portainer

- name: Ensure Portainer compose is running
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /opt/portainer
  changed_when: true
