---
- name: Deploy monitoring stack
  hosts: monitoring
  become: true
  gather_facts: true

  roles:
    - lvm-resize
    - docker
    - monitoring

- name: Deploy monitoring agents
  hosts: docker
  become: true
  gather_facts: true

  roles:
    - alloy-agent
