---
- name: Create docker-apps directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: homelab
    group: homelab
    mode: '0755'
  loop:
    - "{{ docker_apps_dir }}"
    - "{{ docker_apps_dir }}/front"
    - "{{ docker_apps_dir }}/api"

- name: Open firewall ports for docker-apps
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 3000/tcp
    - 8080/tcp
  become: true

- name: Deploy Docker Apps Compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_apps_dir }}/docker-compose.yml"
    owner: homelab
    group: homelab
    mode: '0644'
  notify: Restart docker-apps

- name: Ensure Docker Apps compose is running
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ docker_apps_dir }}"
  changed_when: true
