---
homelab_user: homelab
homelab_timezone: Europe/Warsaw
homelab_domain: lab
homelab_service_root: /srv

# Istniejące stosy są przejmowane osobno. Ustawienie flagi na true oznacza,
# że odpowiednia rola może zapisać Compose i zarządzać kontenerami usługi.
deploy_pihole: true
deploy_jellyfin: false
deploy_proxy: true
deploy_apps: false
deploy_homepage: true
deploy_portainer: true
deploy_nagios: true

pihole_root: /opt/pihole
pihole_image: pihole/pihole@sha256:1c32c36b862a12762656b6471c854cebc01fe945639ba3a893611337c2c95e99
pihole_dns_hosts:
  - "192.168.60.141 dns-01.lab pihole.lab"
  - "192.168.60.144 monitor-01.lab monitoring-01.lab nagios.lab"
  - "192.168.60.142 proxy-01.lab traefik.lab homepage.lab paperless.lab seafile.lab portainer.lab actual.lab jellyfin.lab seerr.lab"
  - "192.168.60.143 app-01.lab app.lab"
  - "192.168.60.131 jelly-01.lab sonarr.lab radarr.lab prowlarr.lab bazarr.lab qbittorrent.lab"
  - "192.168.60.147 homeassistant-01.lab homeassistant.lab"
jellyfin_image: jellyfin/jellyfin:10.11.11
proxy_root: /opt/traefik
traefik_image: traefik@sha256:2cd5cc75530c8d07ae0587c743d23eb30cae2436d07017a5ff78498b1a43d09f
nagios_image: jasonrivers/nagios:latest

homepage_root: /opt/homepage
homepage_port: 3000
homepage_image: ghcr.io/gethomepage/homepage@sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401

portainer_root: /opt/portainer
portainer_image: portainer/portainer-ce@sha256:bd8f7a6d98e2a512e18272c38914abd1e92d663451f3c925d502a8557a3b92d7

jellyfin_data_device: /dev/sdb
jellyfin_data_mount: /srv/jellyfin-data
