---
homelab_user: homelab
homelab_timezone: Europe/Warsaw
homelab_domain: lab
homelab_service_root: /srv

# Istniejące stosy są przejmowane osobno. Ustawienie flagi na true oznacza,
# że odpowiednia rola może zapisać Compose i zarządzać kontenerami usługi.
deploy_pihole: true
deploy_jellyfin: false
deploy_proxy: true
deploy_apps: false
deploy_homepage: true
deploy_portainer: true
deploy_actual: true
deploy_paperless: true
deploy_nagios: true

pihole_root: /opt/pihole
pihole_image: pihole/pihole@sha256:1c32c36b862a12762656b6471c854cebc01fe945639ba3a893611337c2c95e99
pihole_dns_hosts:
  - "192.168.60.141 dns-01.lab pihole.lab"
  - "192.168.60.144 monitor-01.lab monitoring-01.lab nagios.lab"
  - "192.168.60.142 proxy-01.lab traefik.lab homepage.lab paperless.lab seafile.lab portainer.lab actual.lab jellyfin.lab seerr.lab"
  - "192.168.60.143 app-01.lab app.lab"
  - "192.168.60.131 jelly-01.lab sonarr.lab radarr.lab prowlarr.lab bazarr.lab qbittorrent.lab"
  - "192.168.60.147 homeassistant-01.lab homeassistant.lab"
jellyfin_image: jellyfin/jellyfin:10.11.11
proxy_root: /opt/traefik
traefik_image: traefik@sha256:2cd5cc75530c8d07ae0587c743d23eb30cae2436d07017a5ff78498b1a43d09f
nagios_image: jasonrivers/nagios:latest

homepage_root: /opt/homepage
homepage_port: 3000
homepage_image: ghcr.io/gethomepage/homepage@sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401

portainer_root: /opt/portainer
portainer_image: portainer/portainer-ce@sha256:bd8f7a6d98e2a512e18272c38914abd1e92d663451f3c925d502a8557a3b92d7

actual_root: /opt/actual
actual_port: 5006
actual_image: actualbudget/actual-server@sha256:1aeeb3985db55556e716dec25e08f6ce09308c2571b65cddbc6746ee6d5e0d45

paperless_root: /opt/paperless
paperless_data_root: /srv/data/paperless
paperless_port: 8001
paperless_redis_image: redis@sha256:3e1b24a1a8f24ff926b15e5ace8c38a03e5657fb66e1fc7e5188e315aa5fa094
paperless_postgres_image: postgres@sha256:972eeb4e0a5fee4c3046cf868896719227e845aa9e38ff79a353efb3b2b2c10a
paperless_gotenberg_image: gotenberg/gotenberg@sha256:a40c5a46b79d812ce2f5e139278163142a054050bfd1e5f162da36d3d11c7138
paperless_tika_image: apache/tika@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583
paperless_image: ghcr.io/paperless-ngx/paperless-ngx@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f

jellyfin_data_device: /dev/sdb
jellyfin_data_mount: /srv/jellyfin-data
